version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_postgres
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: password_postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_mongo
      MONGO_INITDB_ROOT_PASSWORD: password_mongo
      MONGO_INITDB_DATABASE: db_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: user_mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: password_mongo

  adminer:
    image: adminer
    ports:
      - "8080:8080"


volumes:
  postgres_data:
  mongo_data:

